### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by Justsoos** [CGDF-Github/SSRR-Windows#10]
两个建议：
第一，可以设置里关掉服务器延迟和错误的 tcp 探测功能。看：
```
$netstat -na|wc
   1155    4516   75506
```
打开软件，就有1000+的 tcp 连接，而且还有大量是 pending 状态。这不仅给网络造成很大压力，还让 gfw 探测有了更好的指标。
另，我有200左右节点。

第二，在服务器统计窗口，可以多选节点后，删除，或导出。这个功能 SSRR 的阿卡琳那边 一直没有加上去，相当有用的功能。

**Comment by Justsoos** [comment]
不和傻逼一般见识，88

**Comment by CGDF-Github** [comment]
傻屌issue，本人和头像一样是个盲人，敲点命令行就觉得自己多牛逼，搞得好像老子有义务给你加新功能一样。你非要认我作你爹，给你尽9年义务教育，老子还不想教你个傻逼呢
