### ISSUE TITLE
5.15 版本切换节点没有立即生效，我录了一个视频来复现问题。请看

### ISSUE THREAD

**Issue by discusssth** [CGDF-Github/SSRR-Windows#13]
![image](https://user-images.githubusercontent.com/45059308/48533711-86ff5980-e8e0-11e8-896c-a35a48438be6.png)
 
 这个功能在5.0.0版本已经修好，但是在5.1.5仍然是失效的。
----------------
视频地址：https://mega.nz/#!E2xRnCLL!s2XNjpQkE-SyLV-9ibmzGyVIS-ELjBXDDAbWpPOEE0Q

**Comment by discusssth** [comment]
@CGDF-Github  视频总长3:14秒  ， 谢谢。

**Comment by discusssth** [comment]
确实，通过右下角菜单切换节点是有效的。

能不能把统计面板的切换也加上这个功能呢。 
非常有用。

**Comment by CGDF-Github** [comment]
本项目已不再【新增功能/修改设计】，仅接收bug反馈

**Comment by discusssth** [comment]
这么狠心吗，SSR一脉就剩你一个了啊。

**Comment by CGDF-Github** [comment]
我身上的项目实在过多，没有多余的精力继续改进这个项目。
继续无偿维护本项目的issue和bug已是仁至义尽。
SSR近两千fork，不差我一个。[上游项目](https://github.com/shadowsocksrr/shadowsocksr-csharp)并未停止更新，有功能性需求请尝试发至上游。

**Comment by CGDF-Github** [comment]
我身上的项目实在过多，没有多余的精力继续改进这个项目。
继续无偿维护本项目的issue和bug已是仁至义尽。
SSR近两千fork，不差我一个。[上游项目](https://github.com/shadowsocksrr/shadowsocksr-csharp)并未停止更新，有功能性需求请尝试发至上游。
