### ISSUE TITLE
5.1.5版本，浏览器访问Instagram不显示用户头像,无论是什么模式。

### ISSUE THREAD

**Issue by aefan** [CGDF-Github/SSRR-Windows#17]
我猜测是PAC文件很久没有添加变动了，因此建议内置的GFWlist更换成Koolshare的规则。

**Comment by zhenlinhgs** [comment]
5.15win版本的SSR没办法打开Instagram，图片和视频都显示不出来，
日志那边显示
[2019-02-09 19:06:07] [Error] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Util.Utils.QueryDns(String host, String dns_servers, Boolean IPv6_first)
   在 Shadowsocks.Controller.Handler.Connect()
   在 Shadowsocks.Controller.ProxyAuthHandler.Connect()
   在 Shadowsocks.Controller.ProxyAuthHandler.HandshakeReceive()
[2019-02-09 19:06:08] [Error] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Util.Utils.QueryDns(String host, String dns_servers, Boolean IPv6_first)
   在 Shadowsocks.Controller.Handler.Connect()
   在 Shadowsocks.Controller.ProxyAuthHandler.Connect()
   在 Shadowsocks.Controller.ProxyAuthHandler.HandshakeReceive()
![mzkewp oh f4y d qj7hd](https://user-images.githubusercontent.com/36321109/52519921-f0072b00-2c9d-11e9-8062-e5f88241b521.png)这是怎么回事啊，其他版本都没这问题

**Comment by CGDF-Github** [comment]
请尝试将DNS暂时切换到114，并勾选以下选项
![tim 20190210144454](https://user-images.githubusercontent.com/17256673/52530649-7fb2e500-2d43-11e9-9c61-58b1ae184248.jpg)
然后**重启SSRR**或**随便切换一下节点**

**Comment by zhenlinhgs** [comment]
①代理规则  开了 全局，②系统代理模式也开了全局模式，但是一样，INS没办法显示图片和视频，同样的节点，同样的设置，其他版本可以正常显示INS的图片和视频就是5.15版本的没办法显示

**Comment by aefan** [comment]
> 请尝试将DNS暂时切换到114，并勾选以下选项
> ![tim 20190210144454](https://user-images.githubusercontent.com/17256673/52530649-7fb2e500-2d43-11e9-9c61-58b1ae184248.jpg)
> 然后**重启SSRR**或**随便切换一下节点**

试过了。。全局模式，换节点，一样Ins有毛病。只有老版本的正常。

**Comment by zhenlinhgs** [comment]
嗯，新版本的ins用不了

**Comment by zhenlinhgs** [comment]
嗯，这应该是SSR的APP的问题吧

**Comment by CGDF-Github** [comment]
DNS也试过了？难道5.1.3能用？还是说4.x.x能用？

**Comment by aefan** [comment]
> DNS也试过了？难道5.1.3能用？还是说4.x.x能用？

我路由器和系统都设置114DNS的。确定。

**Comment by zhenlinhgs** [comment]
DNS改了也用不了的，4XX版本的可以用

**Comment by zhenlinhgs** [comment]
5XX版本的就不行

**Comment by aefan** [comment]
> DNS也试过了？难道5.1.3能用？还是说4.x.x能用？
5.1.3版本一切正常。但是5.1.5就INS出毛病。

**Comment by zhenlinhgs** [comment]
5.13版本要去哪里下载啊？

**Comment by aefan** [comment]
> 5.13版本要去哪里下载啊？

https://github.com/CGDF-Github/SSRR-Windows/releases

**Comment by aefan** [comment]
我是前天测试5.1.5出问题的。。刚才我又试了试5.1.5，可以了。。。打扰了，请忽略我的智障Issue.

**Comment by zhenlinhgs** [comment]
我刚刚测试的还不行啊5.15的

**Comment by zhenlinhgs** [comment]
5.15的现在确实可以了，然后  5.13的那个版本，现在不行了，我刚刚下载试了下，5.13不行

**Comment by zhenlinhgs** [comment]
可以了

**Comment by CGDF-Github** [comment]
我倾向于认为是你们哪里操作错了，两个切换到全局之后需要重启一下SSRR

**Comment by aefan** [comment]
![image](https://user-images.githubusercontent.com/46080936/52530941-c8b96800-2d48-11e9-85a1-15199bfb29ff.png)
我收回，，，，问题依旧。

**Comment by aefan** [comment]
刚才是缓存的问题，现在又来了。。。

**Comment by zhenlinhgs** [comment]
是啊，怎么才可以了一会又不行了

**Comment by aefan** [comment]
5.1.5版本：114DNS。全局。重启SSRR。重启系统。chrome浏览器上ins，不显示图片。描述完毕。

**Comment by CGDF-Github** [comment]
是否方便远程看下之类的

**Comment by aefan** [comment]
> 是否方便远程看下之类的
![image](https://user-images.githubusercontent.com/46080936/52531039-17b3cd00-2d4a-11e9-90fb-4ca881cfce7c.png)

**Comment by aefan** [comment]
> 是否方便远程看下之类的

我Q3137654496

**Comment by aefan** [comment]
![image](https://user-images.githubusercontent.com/46080936/52531099-25b61d80-2d4b-11e9-860c-fbd34687ef48.png)

**Comment by CGDF-Github** [comment]
emmm算是一个小常识吧，DNS第一行建议使用8.8.8.8/8.8.4.4/1.1.1.1之类的，114是用在第二行的

**Comment by zhenlinhgs** [comment]
哦，114不是用在第一行啊

**Comment by zhenlinhgs** [comment]
修改了DNS之后确实是可以了，不过，这样修改会影响电脑国内的网速啊，能不能在不修改DNS的情况下（选择自动获取DNS）可以正常使用Instagram

**Comment by CGDF-Github** [comment]
这个为毛会影响国内网速。。。你开PAC模式不就行了

**Comment by zhenlinhgs** [comment]
哦，就是感觉换了DNS之后开淘宝京东那些网站好像有点卡的样子

**Comment by cxgreat2014** [comment]
这个问题很奇怪，刚刚在打开谷歌时遇到相同的问题，找到这个issue之后我并没有更改代理规则，依然是绕过局域网和大陆，直接应用的DNS修改（由默认dhcp获取变成手动指定8.8.8.8和114.114.114.114），之后直接刷新页面解决问题。。

从日志来看感觉更偏向于软件的BUG，除了Instagram的头像问题之外现在谷歌主站，感觉可能影响的站点还是蛮广的

**Comment by aefan** [comment]
没几天又出问题的…我目前已经不用这个分支了。

**Comment by KhaosChow** [comment]
我也有这个问题，试了各种办法，只有把系统dns换为1.1.1.1才能正常显示，在SSR的选项填dns、切换服务器、全局模式都不起作用。

**Comment by jiapengwen** [comment]
||https://avatars\*\.githubusercontent.com  
写在user-rule.txt 中， 然后在ss中，pac/更新本地pac， 头像获取header 可能会变，用正则更好
