### ISSUE TITLE
关于SSR一直有②问题请问下,有劳了谢谢!

### ISSUE THREAD

**Issue by dnknn** [CGDF-Github/SSRR-Windows#9]
@CGDF-Github 

### ❓1️⃣  请问下SSR退出后, 为何任务管理器还会残留一个`privoxy.exe`进程呢?
         这个privoxy.exe残留的作用是什么呢, 可以手动退出吗?
![image](https://user-images.githubusercontent.com/10995302/45914832-2a9e3180-be7d-11e8-8cd8-37f90c5ca627.png)

![1](https://user-images.githubusercontent.com/10995302/45914750-ee1e0600-be7b-11e8-8863-37870de8d035.png)

我用的Chrome浏览器是便携版,顺便让SSR跟随Chrome启动的.
![image](https://user-images.githubusercontent.com/10995302/45914858-9da7a800-be7d-11e8-949f-fe93f0eb40ee.png)
所以如果SSR退出还残留着进程, 下次就无法跟随Chrome启动了.

---

### ❓2️⃣  请问下保持当前状态不修改, 貌似还会改动Win10系统的代理啊?
![image](https://user-images.githubusercontent.com/10995302/45914905-3f2ef980-be7e-11e8-9542-443ec0302c73.png)

一般挂SSR只在Chrome浏览器用SwitchyOmega扩展进行翻`墙的.
所以问问如何设置选项才能不动Win10系统代理呢?

---
有劳了,谢谢!

**Comment by Justsoos** [comment]
你这个截图名字看起来，应该不是本fork，这个fork 应该是 "SoDa-GitHub\temp\ShadowsocksR.exe" 是 开 http 代理端口的 privoxy。
这个进程没退干净，再打开ssr，有时候会引发错误

**Comment by Justsoos** [comment]
相关 bug 可以复现，而且是个顽固 bug https://github.com/shadowsocksrr/shadowsocksr-csharp/issues/142

**Comment by CGDF-Github** [comment]
@Justsoos 说话麻烦动动脑子，很明显这个issue提的是两个问题，而我也是一一对应回复的。我他妈说的是第二个问题无法复现

**Comment by Justsoos** [comment]
您这样的鸟脾气，会得抑郁症的，要么也是焦虑症。
这就是一个bug，我验证过的。
要当混蛋，回你妈的怀里去当，这里不养你这样的。
装什么驴？谁稀罕你？你丫头养的，好赖不知？还是你就是反社会人格？
SB

**Comment by CGDF-Github** [comment]
@Justsoos 头像戴眼镜，看来自己也是个盲人，也不看看自己提你妈的什么JB issue，issue template里是哪个字不认识？还是你的幼儿园学历不足以阅读大量汉字？

**Comment by dnknn** [comment]
> 1：当SSRR被【非正常手段退出】时，会导致privoxy.exe不会自动关闭，不过这个理论上不会影响下一次SSRR启动
> .2：无法复本此异常，请确认你的操作步骤是否正确：{ 
> 打开SSRR，代理将模式e月刊为【保持当前状态不修改】....

1. 都是正常退出, 即手动右键托盘的SSR图标→退出.

2.保持当前状态不修改. 真正意思就是说在当前状态不再改动了.
![image](https://user-images.githubusercontent.com/10995302/45923431-57535700-bf18-11e8-94b4-f05fb6a1dc78.png)

如果先是选择全局模式, 再去勾选【保持当前状态不修改】是没意义了.
因为勾选全[全局模式]后,就触发了系统代理的修改, 所以【保持当前状态不修改】 也就不去动了.

总之就是说【保持当前状态不修改】 永远是先保持当前的现在状态 然后不去修改.

**Comment by CGDF-Github** [comment]
【2】我是说让你按照我提供的步骤做一下，确认一下结果是否正确无异常
